server:
  port: '8081'
  shutdown: graceful

application:
  kafka:
    topic: "testTopic"
    bootstrap-servers: "localhost:9092"

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver

  h2:
    console.enabled: true

  kafka:
    consumer:
      auto-offset-reset: earliest
      group-id: "notesapp"
