@startuml

title "Update note"

actor Client as client
participant Controller as controller
participant Service as service
participant Repository as repository
participant DB as db

client -> controller: PUT /notes
note left
NoteView {
  "id": 1
  "title": "new title",
  "content": "new content"
}
end note
controller -> service: updateNote
service -> service: convertNote
service -> repository: existsById
repository -> service: /true/
service -> repository: save
repository -> db: /query/
db -> repository: /query result/
repository -> service: NotePo
note right
saved note:
NotePo {
  "id": 1
  "title": "new title",
  "content": "new content"
}
end note
service -> service: convertNote
service -> controller: NoteView
controller -> client: NoteView

@enduml