server:
  port: '8080'
  shutdown: graceful

spring:
  datasource:
    url: jdbc:postgresql://notes_app_service_user:HTwTtkl01klKCgxBDUO3oeMiCt2AGrsY@dpg-cekdu8ta4991ihh13nc0-a/notes_app_db_y0gx
    username: notes_app_service_user
    password: HTwTtkl01klKCgxBDUO3oeMiCt2AGrsY
    driverClassName: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

management:
  server:
    port: '${server.port}'
  endpoint:
    health:
      show-details: always
      status:
        http-mapping:
          down: 503
          out-of-service: 429
          up: 200
          unknown: 200
  endpoints:
    web:
      exposure:
        include: "*"
