version: '3.7'

services:

  notes-app-server:
    image: notes-app-server
    environment:
      - JAVA_OPTS=
        -Dspring.profiles.active=docker
        -Dspring.config.location=/opt/local/notes-app/config/application-docker.yml
    volumes:
      - ./configs/notes-app-server:/opt/local/notes-app/config
      - ~/data/docker/notes-app/log:/opt/local/notes-app/log
    networks:
      - app-network
    deploy:
      replicas: 2
    ports:
      - "8080"
    depends_on:
      - kafka
      - consul

  notes-app-statistic:
    image: notes-app-statistic
    environment:
      - JAVA_OPTS=
        -Dspring.profiles.active=docker
        -Dspring.config.location=/opt/local/notes-app-statistic/config/application-docker.yml
    volumes:
      - ./configs/notes-app-statistic:/opt/local/notes-app-statistic/config
      - ~/data/docker/notes-app/log:/opt/local/notes-app-statistic/log
    networks:
      - app-network
    deploy:
      replicas: 2
    ports:
      - "8081"
    depends_on:
      - kafka
      - consul

  python-server:
    container_name: python-server
    image: python-server:latest
    ports:
      - "5050:5000"
    networks:
      - app-network
    depends_on:
      - consul

  consul:
    image: hashicorp/consul:latest
    container_name: consul
    environment:
      - "CONSUL_BIND_INTERFACE=eth0"
    networks:
      - app-network
    expose:
      - "8500"
      - "8600/tcp"
      - "8600/udp"
    ports:
      - "12220:8500"
    volumes:
      - ./configs/python-server:/consul/config/

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    expose:
      - "2181"
    networks:
      - app-network
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      - app-network

    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_INTERNAL://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LOG4J_ROOT_LOGLEVEL: ERROR

networks:
  app-network:
    driver: bridge