server:
  port: '8080'
  shutdown: graceful

spring:
  application:
    name: 'notesapp'
    datasource:
      url: jdbc:h2:mem:mydb
      username: sa
      password: password
      driverClassName: org.h2.Driver

    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
        ddl-auto: create-drop
      properties:
        javax:
          persistence:
            schema-generation:
              action: create
              create-script-source: db.migration/create.sql

    h2:
      console.enabled: true

management:
  server:
    port: '${server.port}'
  endpoint:
    health:
      show-details: always
      status:
        http-mapping:
          down: 503
          out-of-service: 429
          up: 200
          unknown: 200
  endpoints:
    web:
      exposure:
        include: "*"
