@startuml

title "Get one note"

actor Client as client
participant Controller as controller
participant Service as service
participant Repository as repository
participant DB as db

client -> controller: GET /notes/1
controller -> service: getByID
service -> repository: findById
repository -> db: /query/
db -> repository: /query result/
repository -> service: NotePo
note right
NotePo {
  "id": 1,
  "title": "title",
  "content": "content"
}
end note
service -> service: convertNote
service -> controller: NoteView
controller -> client: NoteView


@enduml